# Generated by Django 5.1.5 on 2025-02-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='mail',
            new_name='email',
        ),
    ]
