# Generated by Django 5.1.5 on 2025-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_mail_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='main_app/templates/main_app/static/images/'),
        ),
    ]
